version: '3.9'

volumes:
  caddy_data:
  caddy_conf:

services:
  caddy:
    environment:
      DOMAIN: ${RELAY_URL:-localhost}
      EMAIL: ${CERTBOT_EMAIL}
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
      UPSTREAM_NAME: ${UPSTREAM_NAME:-relay}
      UPSTREAM_PORT: ${UPSTREAM_PORT:-5000}
      LOG_LEVEL: ${LOG_LEVEL:-ERROR}
    volumes:
      - ./stats.html:/www/index.html
    deploy:
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
          - "node.role==manager"

  relay:
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      RELAY_MODE: ${RELAY_MODE:-legacy}
    deploy:
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
          - "node.role==worker"

  redis:
    deploy:
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
          - "node.role==worker"

  waku:
    deploy:
      replicas: 0
